try{
    let a=10
    getlist()
    console.log(a)
}catch(error){
    console.log('errr')

}